### ISSUE TITLE
调用puppeteer时报错

### ISSUE THREAD

**Issue by Kwisma** [ningmengchongshui/alemon#2]
生成图片后报错以下代码

```bash
[ALMB] [2023-05-13 02:17:55] [75024] [INFO] [HTML][CREATE] /root/alemon-bot/data/test-plugin/html/help/help.html
[ALMB] [2023-05-13 02:17:55] [75024] [INFO] [puppeteer]准备开始~
[ALMB] [2023-05-13 02:17:57] [75024] [INFO] [HTML][UPDATA] /root/alemon-bot/data/test-plugin/html/help/help.html
[ALMB] [2023-05-13 02:18:04] [75024] [INFO] [puppeteer]成功启动！
[ALMB] [2023-05-13 02:18:04] [75024] [INFO] [puppeteer]开始截图~
[ALMB] [2023-05-13 02:18:06] [75024] [ERRO] ProtocolError: Protocol error (Runtime.callFunctionOn): Target closed
    at new Callback (/root/alemon-bot/node_modules/puppeteer-core/src/common/Connection.ts:65:12)
    at CallbackRegistry.create (/root/alemon-bot/node_modules/puppeteer-core/src/common/Connection.ts:126:22)
    at Connection._rawSend (/root/alemon-bot/node_modules/puppeteer-core/src/common/Connection.ts:266:22)
    at CDPSessionImpl.send (/root/alemon-bot/node_modules/puppeteer-core/src/common/Connection.ts:525:29)
    at ExecutionContext._ExecutionContext_evaluate (/root/alemon-bot/node_modules/puppeteer-core/src/common/ExecutionContext.ts:305:44)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ExecutionContext.evaluate (/root/alemon-bot/node_modules/puppeteer-core/src/common/ExecutionContext.ts:187:12)
    at async CDPJSHandle.evaluate (/root/alemon-bot/node_modules/puppeteer-core/src/common/JSHandle.ts:74:12)
    at async CDPElementHandle.isIntersectingViewport (/root/alemon-bot/node_modules/puppeteer-core/src/api/ElementHandle.ts:863:14)
    at async CDPElementHandle._CDPElementHandle_scrollIntoViewIfNeeded (/root/alemon-bot/node_modules/puppeteer-core/src/common/ElementHandle.ts:291:7)
```

**Comment by Lycofuture** [comment]
还有`npm run logs`后输出的pm2整体的运行日志，并不是单独`alemon-bot`的日志

**Comment by ningmengchongshui** [comment]
可以考虑配置app.config.ts配置浏览器地址,该问题正在努力寻找优化中....
