### ISSUE TITLE
后台运行报错

### ISSUE THREAD

**Issue by Kwisma** [ningmengchongshui/alemon#3]
前台运行没有问题，但是`npm run start`后台运行后查看日志有报错
错误日志:
```
/root/alemon-bot/logs/alemont/err.log last 15 lines:
5|alemont  | TypeError: Converting circular structure to JSON               5|alemont  |     --> starting at object with constructor 'SourceFileObject'
5|alemont  |     |     property 'statements' -> object with constructor 'Array'
5|alemont  |     |     index 0 -> object with constructor 'NodeObject'
5|alemont  |     --- property 'parent' closes the circle
5|alemont  |     at stringify (<anonymous>)
5|alemont  |     at writeChannelMessage (node:internal/child_process/serialization:159:20)
5|alemont  |     at process.target._send (node:internal/child_process:838:17)
5|alemont  |     at process.target.send (node:internal/child_process:738:19)
5|alemont  |     at process.send (/usr/local/lib/node_modules/pm2/lib/ProcessContainer.js:52:21)
5|alemont  |     at process.uncaughtListener (/usr/local/lib/node_modules/pm2/lib/ProcessContainer.js:276:19)
5|alemont  |     at process.emit (node:events:525:35)                       5|alemont  |     at process.emit (node:domain:489:12)
5|alemont  |     at process.emit.sharedData.processEmitHook.installedValue [as emit] (/usr/local/lib/node_modules/ts-node/node_modules/@cspotcode/source-map-support/source-map-support.js:745:40)                                  5|alemont  |     at process._fatalException (node:internal/process/execution:149:25)
```

**Comment by ningmengchongshui** [comment]
错误无法定位，建议联系  企鹅1715713638面面咨询

**Comment by ningmengchongshui** [comment]
pm2 update  #更新最新版
pm2 kill   #杀死所有进程
rm -rf ~/.pm2  #删除后重新启动即可
